#ifndef MREPORT_ENGINE_EXPORT_H
#define MREPORT_ENGINE_EXPORT_H

#ifdef EXPORT_LIB_MREPORTENGINE
#define EXPORT_MREPORTENGINE Q_DECL_EXPORT
#else
#define EXPORT_MREPORTENGINE Q_DECL_IMPORT
#endif

#endif // MREPORT_ENGINE_EXPORT_H
