#ifndef DEPARTMENT_EXPORT_LIB_H
#define DEPARTMENT_EXPORT_LIB_H

#ifdef EXPORT_LIB_DEPARTMENT
#define EXPORT_DEPARTMENT Q_DECL_EXPORT
#else
#define EXPORT_DEPARTMENT Q_DECL_IMPORT
#endif

#endif // DEPARTMENT_EXPORT_LIB_H
