#ifndef DIRECTION_LIB_EXPORT_H
#define DIRECTION_LIB_EXPORT_H

#ifdef EXPORT_LIB_DIRECTION
#define EXPORT_DIRECTION Q_DECL_EXPORT
#else
#define EXPORT_DIRECTION Q_DECL_IMPORT
#endif

#endif // DIRECTION_LIB_EXPORT_H
