#ifndef GROUP_LIB_EXPORT_H
#define GROUP_LIB_EXPORT_H

#ifdef EXPORT_LIB_DIRECTION
#define EXPORT_DIRECTION Q_DECL_EXPORT
#else
#define EXPORT_DIRECTION Q_DECL_IMPORT
#endif

#endif // GROUP_LIB_EXPORT_H
