#ifndef DOCMANAGER_EXPORT_H
#define DOCMANAGER_EXPORT_H

#ifdef DOCMANAGER_LIBRARY
#define DOCMANAGER_EXPORT Q_DECL_EXPORT
#else
#define DOCMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // DOCMANAGER_EXPORT_H
