#ifndef DOCMANAGERWIDGETS_EXPORT_LIB_H
#define DOCMANAGERWIDGETS_EXPORT_LIB_H

#ifdef DOCMANAGERWIDGETS_LIBRARY
#define EXPORT_DOCMANAGERWIDGETS Q_DECL_EXPORT
#else
#define EXPORT_DOCMANAGERWIDGETS Q_DECL_IMPORT
#endif

#endif // DOCMANAGERWIDGETS_EXPORT_LIB_H
