#ifndef HTMLREPORTLOADER_EXPORT_H
#define HTMLREPORTLOADER_EXPORT_H

#include <QtCore/qglobal.h>

#if defined(HTMLREPORTLOADER_LIBRARY)
#  define HTMLREPORTLOADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HTMLREPORTLOADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HTMLREPORTLOADER_EXPORT_H
