#ifndef HTMLREPORT_EXPORT_H
#define HTMLREPORT_EXPORT_H

#ifdef HTMLREPORT_LIBRARY
#define HTMLREPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#define HTMLREPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HTMLREPORT_EXPORT_H
