#ifndef MFCCORE_EXPORT_LIB_H
#define MFCCORE_EXPORT_LIB_H

#ifdef EXPORT_LIB_MFCCORE
#define EXPORT_MFCCORE Q_DECL_EXPORT
#else
#define EXPORT_MFCCORE Q_DECL_IMPORT
#endif

#endif // MFCCORE_EXPORT_LIB_H
