#ifndef MFCGUIDELOADER_LIB_EXPORT_H
#define MFCGUIDELOADER_LIB_EXPORT_H

#ifdef EXPORT_LIB_MFCGUIDELOADER
#define EXPORT_MFCGUIDELOADER Q_DECL_EXPORT
#else
#define EXPORT_MFCGUIDELOADER Q_DECL_IMPORT
#endif

#endif // MFCGUIDELOADER_LIB_EXPORT_H
