#ifndef MMODELS_EXPORT_LIB_H
#define MMODELS_EXPORT_LIB_H

#ifdef EXPORT_LIB_MMODELS
#define EXPORT_MMODELS Q_DECL_EXPORT
#else
#define EXPORT_MMODELS Q_DECL_IMPORT
#endif

#endif // MMODELS_EXPORT_LIB_H
