#ifndef FTPENGINE_EXPORT_H
#define FTPENGINE_EXPORT_H

#ifdef FTPENGINE_LIBRARY
#define FTPENGINE_EXPORT Q_DECL_EXPORT
#else
#define FTPENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // FTPENGINE_EXPORT_H
